Description: Vini EKS Cluster

Parameters:

  Proj:
    Type: String
    Default: vini

  Env:
    Type: String
    Default: dev

Resources:

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub ${Proj}-${Env}
      RoleArn: !GetAtt ClusterServiceRole.Arn
      Version: 1.17
      ResourcesVpcConfig: 
        SecurityGroupIds:
          !Split
            - ','
            - Fn::ImportValue: 
                !Sub ${Proj}-${Env}-control-plane-sg-list
        SubnetIds:
          !Split
            - ','
            - Fn::ImportValue: 
                !Sub ${Proj}-${Env}-vpc-public-subnets

  ClusterServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${Proj}-${Env}-cluster
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Outputs:

  EksClusterName:
    Description: EKS Cluster Name
    Value: !Ref EksCluster
    Export: 
      Name: !Sub ${Proj}-${Env}-eks-cluster-name

  EksClusterArn:
    Description: EKS Cluster ARN
    Value: !GetAtt EksCluster.Arn
    Export: 
      Name: !Sub ${Proj}-${Env}-eks-cluster-arn

  EksClusterSecurityGroup:
    Description: Cluster Security Group that is created by amazon EKS
    Value: !GetAtt EksCluster.ClusterSecurityGroupId
    Export: 
      Name: !Sub ${Proj}-${Env}-eks-cluster-sg